version = 1

test_patterns = [
  'tests/**'
]

exclude_patterns = [

]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

  [analyzers.meta]
  max_line_length = 119

name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "docker/Dockerfile",
  ]

  trusted_registries = [
    "nvidia",
    "docker.io"
  ]
